//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelFA_WCF_client.WorkClassRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/HotelFA_WCF")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelFA_WCF_client.WorkClassRef.Animal animalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelFA_WCF_client.WorkClassRef.Person clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime datestartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int deliveryfromhotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int deliverytothehotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime deltimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fromdeliveryaddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fromdeliverytimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string todeliveryaddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string todeliverytimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelFA_WCF_client.WorkClassRef.Animal animal {
            get {
                return this.animalField;
            }
            set {
                if ((object.ReferenceEquals(this.animalField, value) != true)) {
                    this.animalField = value;
                    this.RaisePropertyChanged("animal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelFA_WCF_client.WorkClassRef.Person client {
            get {
                return this.clientField;
            }
            set {
                if ((object.ReferenceEquals(this.clientField, value) != true)) {
                    this.clientField = value;
                    this.RaisePropertyChanged("client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                if ((object.ReferenceEquals(this.commentField, value) != true)) {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateend {
            get {
                return this.dateendField;
            }
            set {
                if ((this.dateendField.Equals(value) != true)) {
                    this.dateendField = value;
                    this.RaisePropertyChanged("dateend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime datestart {
            get {
                return this.datestartField;
            }
            set {
                if ((this.datestartField.Equals(value) != true)) {
                    this.datestartField = value;
                    this.RaisePropertyChanged("datestart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int deliveryfromhotel {
            get {
                return this.deliveryfromhotelField;
            }
            set {
                if ((this.deliveryfromhotelField.Equals(value) != true)) {
                    this.deliveryfromhotelField = value;
                    this.RaisePropertyChanged("deliveryfromhotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int deliverytothehotel {
            get {
                return this.deliverytothehotelField;
            }
            set {
                if ((this.deliverytothehotelField.Equals(value) != true)) {
                    this.deliverytothehotelField = value;
                    this.RaisePropertyChanged("deliverytothehotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime deltime {
            get {
                return this.deltimeField;
            }
            set {
                if ((this.deltimeField.Equals(value) != true)) {
                    this.deltimeField = value;
                    this.RaisePropertyChanged("deltime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fromdeliveryaddress {
            get {
                return this.fromdeliveryaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.fromdeliveryaddressField, value) != true)) {
                    this.fromdeliveryaddressField = value;
                    this.RaisePropertyChanged("fromdeliveryaddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fromdeliverytime {
            get {
                return this.fromdeliverytimeField;
            }
            set {
                if ((object.ReferenceEquals(this.fromdeliverytimeField, value) != true)) {
                    this.fromdeliverytimeField = value;
                    this.RaisePropertyChanged("fromdeliverytime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string todeliveryaddress {
            get {
                return this.todeliveryaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.todeliveryaddressField, value) != true)) {
                    this.todeliveryaddressField = value;
                    this.RaisePropertyChanged("todeliveryaddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string todeliverytime {
            get {
                return this.todeliverytimeField;
            }
            set {
                if ((object.ReferenceEquals(this.todeliverytimeField, value) != true)) {
                    this.todeliverytimeField = value;
                    this.RaisePropertyChanged("todeliverytime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Animal", Namespace="http://schemas.datacontract.org/2004/07/HotelFA_WCF")]
    [System.SerializableAttribute()]
    public partial class Animal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelFA_WCF_client.WorkClassRef.AnimalType animaltypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime birthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelFA_WCF_client.WorkClassRef.Person clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime deltimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelFA_WCF_client.WorkClassRef.AnimalType animaltype {
            get {
                return this.animaltypeField;
            }
            set {
                if ((object.ReferenceEquals(this.animaltypeField, value) != true)) {
                    this.animaltypeField = value;
                    this.RaisePropertyChanged("animaltype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime birthday {
            get {
                return this.birthdayField;
            }
            set {
                if ((this.birthdayField.Equals(value) != true)) {
                    this.birthdayField = value;
                    this.RaisePropertyChanged("birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelFA_WCF_client.WorkClassRef.Person client {
            get {
                return this.clientField;
            }
            set {
                if ((object.ReferenceEquals(this.clientField, value) != true)) {
                    this.clientField = value;
                    this.RaisePropertyChanged("client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                if ((object.ReferenceEquals(this.commentField, value) != true)) {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime deltime {
            get {
                return this.deltimeField;
            }
            set {
                if ((this.deltimeField.Equals(value) != true)) {
                    this.deltimeField = value;
                    this.RaisePropertyChanged("deltime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sex {
            get {
                return this.sexField;
            }
            set {
                if ((this.sexField.Equals(value) != true)) {
                    this.sexField = value;
                    this.RaisePropertyChanged("sex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/HotelFA_WCF")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string birthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateofissuetokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string birthday {
            get {
                return this.birthdayField;
            }
            set {
                if ((object.ReferenceEquals(this.birthdayField, value) != true)) {
                    this.birthdayField = value;
                    this.RaisePropertyChanged("birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateofissuetoken {
            get {
                return this.dateofissuetokenField;
            }
            set {
                if ((this.dateofissuetokenField.Equals(value) != true)) {
                    this.dateofissuetokenField = value;
                    this.RaisePropertyChanged("dateofissuetoken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int state {
            get {
                return this.stateField;
            }
            set {
                if ((this.stateField.Equals(value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnimalType", Namespace="http://schemas.datacontract.org/2004/07/HotelFA_WCF")]
    [System.SerializableAttribute()]
    public partial class AnimalType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime deltimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameoftypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime deltime {
            get {
                return this.deltimeField;
            }
            set {
                if ((this.deltimeField.Equals(value) != true)) {
                    this.deltimeField = value;
                    this.RaisePropertyChanged("deltime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameoftype {
            get {
                return this.nameoftypeField;
            }
            set {
                if ((object.ReferenceEquals(this.nameoftypeField, value) != true)) {
                    this.nameoftypeField = value;
                    this.RaisePropertyChanged("nameoftype");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Review", Namespace="http://schemas.datacontract.org/2004/07/HotelFA_WCF")]
    [System.SerializableAttribute()]
    public partial class Review : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelFA_WCF_client.WorkClassRef.AnimalType animaltypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelFA_WCF_client.WorkClassRef.Person clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime createtimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime deltimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelFA_WCF_client.WorkClassRef.AnimalType animaltype {
            get {
                return this.animaltypeField;
            }
            set {
                if ((object.ReferenceEquals(this.animaltypeField, value) != true)) {
                    this.animaltypeField = value;
                    this.RaisePropertyChanged("animaltype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                if ((object.ReferenceEquals(this.bodyField, value) != true)) {
                    this.bodyField = value;
                    this.RaisePropertyChanged("body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelFA_WCF_client.WorkClassRef.Person client {
            get {
                return this.clientField;
            }
            set {
                if ((object.ReferenceEquals(this.clientField, value) != true)) {
                    this.clientField = value;
                    this.RaisePropertyChanged("client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime createtime {
            get {
                return this.createtimeField;
            }
            set {
                if ((this.createtimeField.Equals(value) != true)) {
                    this.createtimeField = value;
                    this.RaisePropertyChanged("createtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime deltime {
            get {
                return this.deltimeField;
            }
            set {
                if ((this.deltimeField.Equals(value) != true)) {
                    this.deltimeField = value;
                    this.RaisePropertyChanged("deltime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMessage", Namespace="http://schemas.datacontract.org/2004/07/HotelFA_WCF")]
    [System.SerializableAttribute()]
    public partial class ChatMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelFA_WCF_client.WorkClassRef.Chat chatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelFA_WCF_client.WorkClassRef.Person clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime deltimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string filepathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime timeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelFA_WCF_client.WorkClassRef.Chat chat {
            get {
                return this.chatField;
            }
            set {
                if ((object.ReferenceEquals(this.chatField, value) != true)) {
                    this.chatField = value;
                    this.RaisePropertyChanged("chat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelFA_WCF_client.WorkClassRef.Person client {
            get {
                return this.clientField;
            }
            set {
                if ((object.ReferenceEquals(this.clientField, value) != true)) {
                    this.clientField = value;
                    this.RaisePropertyChanged("client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime deltime {
            get {
                return this.deltimeField;
            }
            set {
                if ((this.deltimeField.Equals(value) != true)) {
                    this.deltimeField = value;
                    this.RaisePropertyChanged("deltime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string filepath {
            get {
                return this.filepathField;
            }
            set {
                if ((object.ReferenceEquals(this.filepathField, value) != true)) {
                    this.filepathField = value;
                    this.RaisePropertyChanged("filepath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                if ((this.timeField.Equals(value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chat", Namespace="http://schemas.datacontract.org/2004/07/HotelFA_WCF")]
    [System.SerializableAttribute()]
    public partial class Chat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelFA_WCF_client.WorkClassRef.Person clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime deltimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelFA_WCF_client.WorkClassRef.Person client {
            get {
                return this.clientField;
            }
            set {
                if ((object.ReferenceEquals(this.clientField, value) != true)) {
                    this.clientField = value;
                    this.RaisePropertyChanged("client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime deltime {
            get {
                return this.deltimeField;
            }
            set {
                if ((this.deltimeField.Equals(value) != true)) {
                    this.deltimeField = value;
                    this.RaisePropertyChanged("deltime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Journal", Namespace="http://schemas.datacontract.org/2004/07/HotelFA_WCF")]
    [System.SerializableAttribute()]
    public partial class Journal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelFA_WCF_client.WorkClassRef.Animal animalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime deltimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string filepathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelFA_WCF_client.WorkClassRef.Order orderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string taskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime timeendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime timestartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelFA_WCF_client.WorkClassRef.Person workerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelFA_WCF_client.WorkClassRef.Animal animal {
            get {
                return this.animalField;
            }
            set {
                if ((object.ReferenceEquals(this.animalField, value) != true)) {
                    this.animalField = value;
                    this.RaisePropertyChanged("animal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                if ((object.ReferenceEquals(this.commentField, value) != true)) {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime deltime {
            get {
                return this.deltimeField;
            }
            set {
                if ((this.deltimeField.Equals(value) != true)) {
                    this.deltimeField = value;
                    this.RaisePropertyChanged("deltime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string filepath {
            get {
                return this.filepathField;
            }
            set {
                if ((object.ReferenceEquals(this.filepathField, value) != true)) {
                    this.filepathField = value;
                    this.RaisePropertyChanged("filepath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelFA_WCF_client.WorkClassRef.Order order {
            get {
                return this.orderField;
            }
            set {
                if ((object.ReferenceEquals(this.orderField, value) != true)) {
                    this.orderField = value;
                    this.RaisePropertyChanged("order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string task {
            get {
                return this.taskField;
            }
            set {
                if ((object.ReferenceEquals(this.taskField, value) != true)) {
                    this.taskField = value;
                    this.RaisePropertyChanged("task");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime timeend {
            get {
                return this.timeendField;
            }
            set {
                if ((this.timeendField.Equals(value) != true)) {
                    this.timeendField = value;
                    this.RaisePropertyChanged("timeend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime timestart {
            get {
                return this.timestartField;
            }
            set {
                if ((this.timestartField.Equals(value) != true)) {
                    this.timestartField = value;
                    this.RaisePropertyChanged("timestart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelFA_WCF_client.WorkClassRef.Person worker {
            get {
                return this.workerField;
            }
            set {
                if ((object.ReferenceEquals(this.workerField, value) != true)) {
                    this.workerField = value;
                    this.RaisePropertyChanged("worker");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkClassRef.IWorkClasses")]
    public interface IWorkClasses {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getCurrentUser", ReplyAction="http://tempuri.org/IWorkClasses/getCurrentUserResponse")]
        string getCurrentUser(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getCurrentUser", ReplyAction="http://tempuri.org/IWorkClasses/getCurrentUserResponse")]
        System.Threading.Tasks.Task<string> getCurrentUserAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getOrders", ReplyAction="http://tempuri.org/IWorkClasses/getOrdersResponse")]
        HotelFA_WCF_client.WorkClassRef.Order[] getOrders(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getOrders", ReplyAction="http://tempuri.org/IWorkClasses/getOrdersResponse")]
        System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Order[]> getOrdersAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getOrdersByDate", ReplyAction="http://tempuri.org/IWorkClasses/getOrdersByDateResponse")]
        HotelFA_WCF_client.WorkClassRef.Order[] getOrdersByDate(System.DateTime startDate, System.DateTime endDate, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getOrdersByDate", ReplyAction="http://tempuri.org/IWorkClasses/getOrdersByDateResponse")]
        System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Order[]> getOrdersByDateAsync(System.DateTime startDate, System.DateTime endDate, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/changePwd", ReplyAction="http://tempuri.org/IWorkClasses/changePwdResponse")]
        void changePwd(string token, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/changePwd", ReplyAction="http://tempuri.org/IWorkClasses/changePwdResponse")]
        System.Threading.Tasks.Task changePwdAsync(string token, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getPersons", ReplyAction="http://tempuri.org/IWorkClasses/getPersonsResponse")]
        HotelFA_WCF_client.WorkClassRef.Person[] getPersons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getPersons", ReplyAction="http://tempuri.org/IWorkClasses/getPersonsResponse")]
        System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Person[]> getPersonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/addOrder", ReplyAction="http://tempuri.org/IWorkClasses/addOrderResponse")]
        void addOrder(HotelFA_WCF_client.WorkClassRef.Order order, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/addOrder", ReplyAction="http://tempuri.org/IWorkClasses/addOrderResponse")]
        System.Threading.Tasks.Task addOrderAsync(HotelFA_WCF_client.WorkClassRef.Order order, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/addReview", ReplyAction="http://tempuri.org/IWorkClasses/addReviewResponse")]
        void addReview(HotelFA_WCF_client.WorkClassRef.Review review, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/addReview", ReplyAction="http://tempuri.org/IWorkClasses/addReviewResponse")]
        System.Threading.Tasks.Task addReviewAsync(HotelFA_WCF_client.WorkClassRef.Review review, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/addPerson", ReplyAction="http://tempuri.org/IWorkClasses/addPersonResponse")]
        void addPerson(HotelFA_WCF_client.WorkClassRef.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/addPerson", ReplyAction="http://tempuri.org/IWorkClasses/addPersonResponse")]
        System.Threading.Tasks.Task addPersonAsync(HotelFA_WCF_client.WorkClassRef.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/addAnimal", ReplyAction="http://tempuri.org/IWorkClasses/addAnimalResponse")]
        void addAnimal(HotelFA_WCF_client.WorkClassRef.Animal animal, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/addAnimal", ReplyAction="http://tempuri.org/IWorkClasses/addAnimalResponse")]
        System.Threading.Tasks.Task addAnimalAsync(HotelFA_WCF_client.WorkClassRef.Animal animal, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/addMessage", ReplyAction="http://tempuri.org/IWorkClasses/addMessageResponse")]
        void addMessage(HotelFA_WCF_client.WorkClassRef.ChatMessage message, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/addMessage", ReplyAction="http://tempuri.org/IWorkClasses/addMessageResponse")]
        System.Threading.Tasks.Task addMessageAsync(HotelFA_WCF_client.WorkClassRef.ChatMessage message, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/user_auth", ReplyAction="http://tempuri.org/IWorkClasses/user_authResponse")]
        bool user_auth(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/user_auth", ReplyAction="http://tempuri.org/IWorkClasses/user_authResponse")]
        System.Threading.Tasks.Task<bool> user_authAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/logout", ReplyAction="http://tempuri.org/IWorkClasses/logoutResponse")]
        int logout(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/logout", ReplyAction="http://tempuri.org/IWorkClasses/logoutResponse")]
        System.Threading.Tasks.Task<int> logoutAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getAnimals", ReplyAction="http://tempuri.org/IWorkClasses/getAnimalsResponse")]
        HotelFA_WCF_client.WorkClassRef.Animal[] getAnimals(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getAnimals", ReplyAction="http://tempuri.org/IWorkClasses/getAnimalsResponse")]
        System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Animal[]> getAnimalsAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getAnimalTypes", ReplyAction="http://tempuri.org/IWorkClasses/getAnimalTypesResponse")]
        HotelFA_WCF_client.WorkClassRef.AnimalType[] getAnimalTypes(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getAnimalTypes", ReplyAction="http://tempuri.org/IWorkClasses/getAnimalTypesResponse")]
        System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.AnimalType[]> getAnimalTypesAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getAnimalsInHotel", ReplyAction="http://tempuri.org/IWorkClasses/getAnimalsInHotelResponse")]
        HotelFA_WCF_client.WorkClassRef.Animal[] getAnimalsInHotel(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getAnimalsInHotel", ReplyAction="http://tempuri.org/IWorkClasses/getAnimalsInHotelResponse")]
        System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Animal[]> getAnimalsInHotelAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getReview", ReplyAction="http://tempuri.org/IWorkClasses/getReviewResponse")]
        HotelFA_WCF_client.WorkClassRef.Review[] getReview();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getReview", ReplyAction="http://tempuri.org/IWorkClasses/getReviewResponse")]
        System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Review[]> getReviewAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getJournal", ReplyAction="http://tempuri.org/IWorkClasses/getJournalResponse")]
        HotelFA_WCF_client.WorkClassRef.Journal[] getJournal(int animalid, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getJournal", ReplyAction="http://tempuri.org/IWorkClasses/getJournalResponse")]
        System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Journal[]> getJournalAsync(int animalid, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getChatMessages", ReplyAction="http://tempuri.org/IWorkClasses/getChatMessagesResponse")]
        HotelFA_WCF_client.WorkClassRef.ChatMessage[] getChatMessages(int status, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getChatMessages", ReplyAction="http://tempuri.org/IWorkClasses/getChatMessagesResponse")]
        System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.ChatMessage[]> getChatMessagesAsync(int status, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getChatMessagesByDate", ReplyAction="http://tempuri.org/IWorkClasses/getChatMessagesByDateResponse")]
        HotelFA_WCF_client.WorkClassRef.ChatMessage[] getChatMessagesByDate(int status, System.DateTime datestart, System.DateTime dateend, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getChatMessagesByDate", ReplyAction="http://tempuri.org/IWorkClasses/getChatMessagesByDateResponse")]
        System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.ChatMessage[]> getChatMessagesByDateAsync(int status, System.DateTime datestart, System.DateTime dateend, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getAccountWorker", ReplyAction="http://tempuri.org/IWorkClasses/getAccountWorkerResponse")]
        HotelFA_WCF_client.WorkClassRef.Person[] getAccountWorker(int workerid, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getAccountWorker", ReplyAction="http://tempuri.org/IWorkClasses/getAccountWorkerResponse")]
        System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Person[]> getAccountWorkerAsync(int workerid, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getAccount", ReplyAction="http://tempuri.org/IWorkClasses/getAccountResponse")]
        HotelFA_WCF_client.WorkClassRef.Person[] getAccount(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkClasses/getAccount", ReplyAction="http://tempuri.org/IWorkClasses/getAccountResponse")]
        System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Person[]> getAccountAsync(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkClassesChannel : HotelFA_WCF_client.WorkClassRef.IWorkClasses, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkClassesClient : System.ServiceModel.ClientBase<HotelFA_WCF_client.WorkClassRef.IWorkClasses>, HotelFA_WCF_client.WorkClassRef.IWorkClasses {
        
        public WorkClassesClient() {
        }
        
        public WorkClassesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkClassesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkClassesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkClassesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getCurrentUser(string login, string password) {
            return base.Channel.getCurrentUser(login, password);
        }
        
        public System.Threading.Tasks.Task<string> getCurrentUserAsync(string login, string password) {
            return base.Channel.getCurrentUserAsync(login, password);
        }
        
        public HotelFA_WCF_client.WorkClassRef.Order[] getOrders(string token) {
            return base.Channel.getOrders(token);
        }
        
        public System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Order[]> getOrdersAsync(string token) {
            return base.Channel.getOrdersAsync(token);
        }
        
        public HotelFA_WCF_client.WorkClassRef.Order[] getOrdersByDate(System.DateTime startDate, System.DateTime endDate, string token) {
            return base.Channel.getOrdersByDate(startDate, endDate, token);
        }
        
        public System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Order[]> getOrdersByDateAsync(System.DateTime startDate, System.DateTime endDate, string token) {
            return base.Channel.getOrdersByDateAsync(startDate, endDate, token);
        }
        
        public void changePwd(string token, string password) {
            base.Channel.changePwd(token, password);
        }
        
        public System.Threading.Tasks.Task changePwdAsync(string token, string password) {
            return base.Channel.changePwdAsync(token, password);
        }
        
        public HotelFA_WCF_client.WorkClassRef.Person[] getPersons() {
            return base.Channel.getPersons();
        }
        
        public System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Person[]> getPersonsAsync() {
            return base.Channel.getPersonsAsync();
        }
        
        public void addOrder(HotelFA_WCF_client.WorkClassRef.Order order, string token) {
            base.Channel.addOrder(order, token);
        }
        
        public System.Threading.Tasks.Task addOrderAsync(HotelFA_WCF_client.WorkClassRef.Order order, string token) {
            return base.Channel.addOrderAsync(order, token);
        }
        
        public void addReview(HotelFA_WCF_client.WorkClassRef.Review review, string token) {
            base.Channel.addReview(review, token);
        }
        
        public System.Threading.Tasks.Task addReviewAsync(HotelFA_WCF_client.WorkClassRef.Review review, string token) {
            return base.Channel.addReviewAsync(review, token);
        }
        
        public void addPerson(HotelFA_WCF_client.WorkClassRef.Person person) {
            base.Channel.addPerson(person);
        }
        
        public System.Threading.Tasks.Task addPersonAsync(HotelFA_WCF_client.WorkClassRef.Person person) {
            return base.Channel.addPersonAsync(person);
        }
        
        public void addAnimal(HotelFA_WCF_client.WorkClassRef.Animal animal, string token) {
            base.Channel.addAnimal(animal, token);
        }
        
        public System.Threading.Tasks.Task addAnimalAsync(HotelFA_WCF_client.WorkClassRef.Animal animal, string token) {
            return base.Channel.addAnimalAsync(animal, token);
        }
        
        public void addMessage(HotelFA_WCF_client.WorkClassRef.ChatMessage message, string token) {
            base.Channel.addMessage(message, token);
        }
        
        public System.Threading.Tasks.Task addMessageAsync(HotelFA_WCF_client.WorkClassRef.ChatMessage message, string token) {
            return base.Channel.addMessageAsync(message, token);
        }
        
        public bool user_auth(string login, string password) {
            return base.Channel.user_auth(login, password);
        }
        
        public System.Threading.Tasks.Task<bool> user_authAsync(string login, string password) {
            return base.Channel.user_authAsync(login, password);
        }
        
        public int logout(string token) {
            return base.Channel.logout(token);
        }
        
        public System.Threading.Tasks.Task<int> logoutAsync(string token) {
            return base.Channel.logoutAsync(token);
        }
        
        public HotelFA_WCF_client.WorkClassRef.Animal[] getAnimals(string token) {
            return base.Channel.getAnimals(token);
        }
        
        public System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Animal[]> getAnimalsAsync(string token) {
            return base.Channel.getAnimalsAsync(token);
        }
        
        public HotelFA_WCF_client.WorkClassRef.AnimalType[] getAnimalTypes(string token) {
            return base.Channel.getAnimalTypes(token);
        }
        
        public System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.AnimalType[]> getAnimalTypesAsync(string token) {
            return base.Channel.getAnimalTypesAsync(token);
        }
        
        public HotelFA_WCF_client.WorkClassRef.Animal[] getAnimalsInHotel(string token) {
            return base.Channel.getAnimalsInHotel(token);
        }
        
        public System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Animal[]> getAnimalsInHotelAsync(string token) {
            return base.Channel.getAnimalsInHotelAsync(token);
        }
        
        public HotelFA_WCF_client.WorkClassRef.Review[] getReview() {
            return base.Channel.getReview();
        }
        
        public System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Review[]> getReviewAsync() {
            return base.Channel.getReviewAsync();
        }
        
        public HotelFA_WCF_client.WorkClassRef.Journal[] getJournal(int animalid, string token) {
            return base.Channel.getJournal(animalid, token);
        }
        
        public System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Journal[]> getJournalAsync(int animalid, string token) {
            return base.Channel.getJournalAsync(animalid, token);
        }
        
        public HotelFA_WCF_client.WorkClassRef.ChatMessage[] getChatMessages(int status, string token) {
            return base.Channel.getChatMessages(status, token);
        }
        
        public System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.ChatMessage[]> getChatMessagesAsync(int status, string token) {
            return base.Channel.getChatMessagesAsync(status, token);
        }
        
        public HotelFA_WCF_client.WorkClassRef.ChatMessage[] getChatMessagesByDate(int status, System.DateTime datestart, System.DateTime dateend, string token) {
            return base.Channel.getChatMessagesByDate(status, datestart, dateend, token);
        }
        
        public System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.ChatMessage[]> getChatMessagesByDateAsync(int status, System.DateTime datestart, System.DateTime dateend, string token) {
            return base.Channel.getChatMessagesByDateAsync(status, datestart, dateend, token);
        }
        
        public HotelFA_WCF_client.WorkClassRef.Person[] getAccountWorker(int workerid, string token) {
            return base.Channel.getAccountWorker(workerid, token);
        }
        
        public System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Person[]> getAccountWorkerAsync(int workerid, string token) {
            return base.Channel.getAccountWorkerAsync(workerid, token);
        }
        
        public HotelFA_WCF_client.WorkClassRef.Person[] getAccount(string token) {
            return base.Channel.getAccount(token);
        }
        
        public System.Threading.Tasks.Task<HotelFA_WCF_client.WorkClassRef.Person[]> getAccountAsync(string token) {
            return base.Channel.getAccountAsync(token);
        }
    }
}
